// This file was generated by AI(Claude 3.5 Sonnet model)

import { v4 as uuidv4 } from 'uuid';
import { CertificateType } from './types';

export const certificateTypes: CertificateType[] = [
  {
    id: uuidv4(),
    title: 'Basic Safety Training',
    description:
      'Fundamental maritime safety certification required for all seafarers',
  },
  {
    id: uuidv4(),
    title: 'Medical First Aid',
    description: 'Certification for providing medical first aid on board ships',
  },
  {
    id: uuidv4(),
    title: 'Navigation Watch Certificate',
    description: 'Qualification for navigation watch duties',
  },
  {
    id: uuidv4(),
    title: 'Engine Room Watch Certificate',
    description: 'Qualification for engine room watch duties',
  },
  {
    id: uuidv4(),
    title: 'Advanced Firefighting',
    description: 'Advanced training in marine firefighting techniques',
  },
  {
    id: uuidv4(),
    title: 'GMDSS Radio Operator',
    description:
      'Global Maritime Distress and Safety System operation certification',
  },
  {
    id: uuidv4(),
    title: 'Ship Security Officer',
    description: 'Certification for ship security responsibilities',
  },
  {
    id: uuidv4(),
    title: 'Survival Craft Certificate',
    description: 'Operation of survival craft and rescue boats',
  },
  {
    id: uuidv4(),
    title: 'Dangerous Goods Handling',
    description: 'Certification for handling dangerous goods at sea',
  },
  {
    id: uuidv4(),
    title: 'Basic Tanker Operations',
    description: 'Basic training for oil and chemical tanker operations',
  },
  {
    id: uuidv4(),
    title: 'Crowd Management',
    description: 'Training for managing large groups of passengers',
  },
  {
    id: uuidv4(),
    title: 'Ice Navigation',
    description: 'Specialized training for navigation in ice conditions',
  },
  {
    id: uuidv4(),
    title: 'Crane Operations',
    description: 'Certificate for operating ship cranes and lifting equipment',
  },
  {
    id: uuidv4(),
    title: 'Commercial Diving',
    description: 'Professional diving operations certification',
  },
  {
    id: uuidv4(),
    title: 'Environmental Management',
    description: 'Marine environmental protection certification',
  },
  {
    id: uuidv4(),
    title: 'Bridge Team Management',
    description: 'Leadership and management for bridge operations',
  },
  {
    id: uuidv4(),
    title: 'Cargo Handling',
    description: 'Safe cargo operations and handling certification',
  },
  {
    id: uuidv4(),
    title: 'Advanced Medical Care',
    description: 'Advanced medical care provider certification',
  },
  {
    id: uuidv4(),
    title: 'Fast Rescue Boat',
    description: 'Operation of fast rescue boats in emergency situations',
  },
  {
    id: uuidv4(),
    title: 'Polar Code Basic',
    description: 'Basic training for ships operating in polar waters',
  },
  {
    id: uuidv4(),
    title: 'Dynamic Positioning Basic',
    description: 'Basic dynamic positioning operations',
  },
  {
    id: uuidv4(),
    title: "Ship's Cook Certificate",
    description: 'Professional maritime cooking certification',
  },
  {
    id: uuidv4(),
    title: 'Marine Welding',
    description: 'Shipboard welding operations certification',
  },
  {
    id: uuidv4(),
    title: 'Marine Electrical',
    description: "Ship's electrical systems maintenance certification",
  },
  {
    id: uuidv4(),
    title: 'Radar Navigation',
    description: 'Operation of radar equipment and plotting',
  },
  {
    id: uuidv4(),
    title: 'ARPA Operations',
    description: 'Automatic Radar Plotting Aids certification',
  },
  {
    id: uuidv4(),
    title: 'ECDIS Certificate',
    description: 'Electronic Chart Display and Information Systems',
  },
  {
    id: uuidv4(),
    title: 'High Voltage Safety',
    description: 'Safety certification for high voltage systems',
  },
  {
    id: uuidv4(),
    title: 'ROV Operations',
    description: 'Remote Operated Vehicle pilot certification',
  },
  {
    id: uuidv4(),
    title: 'Advanced Crane Operations',
    description: 'Advanced certification for heavy lift operations',
  },
  {
    id: uuidv4(),
    title: 'Advanced Tanker Safety',
    description: 'Advanced oil tanker operations certification',
  },
  {
    id: uuidv4(),
    title: 'Gas Carrier Operations',
    description: 'LNG/LPG carrier operations certification',
  },
  {
    id: uuidv4(),
    title: 'Chemical Tanker Safety',
    description: 'Chemical tanker operations certification',
  },
  {
    id: uuidv4(),
    title: 'ISM Code Management',
    description: 'International Safety Management code certification',
  },
  {
    id: uuidv4(),
    title: 'ISPS Code Training',
    description: 'International Ship and Port Facility Security code',
  },
  {
    id: uuidv4(),
    title: 'MARPOL Operations',
    description: 'Marine pollution prevention certification',
  },
  {
    id: uuidv4(),
    title: 'Advanced Rescue Operations',
    description: 'Complex rescue operations certification',
  },
  {
    id: uuidv4(),
    title: 'Telemedical Care',
    description: 'Remote medical assistance certification',
  },
  {
    id: uuidv4(),
    title: 'Safety Officer',
    description: 'Ship safety officer certification',
  },
  {
    id: uuidv4(),
    title: 'Quality Assurance',
    description: 'Maritime quality management systems',
  },
  {
    id: uuidv4(),
    title: 'Internal Auditor',
    description: 'Maritime internal auditing certification',
  },
  {
    id: uuidv4(),
    title: 'Polar Code Advanced',
    description: 'Advanced polar waters operations',
  },
  {
    id: uuidv4(),
    title: 'Dynamic Positioning Advanced',
    description: 'Advanced DP operations certification',
  },
  {
    id: uuidv4(),
    title: 'Heavy Weather Navigation',
    description: 'Navigation in severe weather conditions',
  },
  {
    id: uuidv4(),
    title: 'Anchor Handling',
    description: 'Anchor handling operations certification',
  },
  {
    id: uuidv4(),
    title: 'Offshore Operations',
    description: 'Basic offshore operations certification',
  },
  {
    id: uuidv4(),
    title: 'Wind Farm Operations',
    description: 'Offshore wind farm support operations',
  },
  {
    id: uuidv4(),
    title: 'Drilling Operations',
    description: 'Offshore drilling operations support',
  },
  {
    id: uuidv4(),
    title: 'Subsea Operations',
    description: 'Subsea equipment handling certification',
  },
  {
    id: uuidv4(),
    title: 'Marine Engineering Basic',
    description: 'Basic marine engineering certification',
  },
  {
    id: uuidv4(),
    title: 'Marine Engineering Advanced',
    description: 'Advanced marine engineering certification',
  },
  {
    id: uuidv4(),
    title: 'Propulsion Systems',
    description: 'Ship propulsion systems management',
  },
  {
    id: uuidv4(),
    title: 'Ballast Water Management',
    description: 'Ballast water treatment operations',
  },
  {
    id: uuidv4(),
    title: 'Fuel Management',
    description: 'Ship fuel systems management',
  },
  {
    id: uuidv4(),
    title: 'Hydraulic Systems',
    description: 'Ship hydraulic systems maintenance',
  },
  {
    id: uuidv4(),
    title: 'Pneumatic Systems',
    description: 'Ship pneumatic systems maintenance',
  },
  {
    id: uuidv4(),
    title: 'Cooling Systems',
    description: 'Ship cooling systems maintenance',
  },
  {
    id: uuidv4(),
    title: 'Boiler Operations',
    description: 'Marine boiler operations certification',
  },
  {
    id: uuidv4(),
    title: 'Turbine Operations',
    description: 'Marine turbine operations certification',
  },
  {
    id: uuidv4(),
    title: 'Generator Management',
    description: 'Ship generator systems management',
  },
  {
    id: uuidv4(),
    title: 'Automation Systems',
    description: 'Ship automation systems certification',
  },
  {
    id: uuidv4(),
    title: 'Control Systems',
    description: 'Ship control systems maintenance',
  },
  {
    id: uuidv4(),
    title: 'PLC Systems',
    description: 'Programmable Logic Controller systems',
  },
  {
    id: uuidv4(),
    title: 'Instrumentation',
    description: 'Marine instrumentation certification',
  },
  {
    id: uuidv4(),
    title: 'Calibration Specialist',
    description: 'Marine equipment calibration certification',
  },
  {
    id: uuidv4(),
    title: 'Non-Destructive Testing',
    description: 'NDT inspection certification',
  },
  {
    id: uuidv4(),
    title: 'Marine Coating Inspector',
    description: 'Marine coating inspection certification',
  },
  {
    id: uuidv4(),
    title: 'Rigging Operations',
    description: 'Marine rigging operations certification',
  },
  {
    id: uuidv4(),
    title: 'Marine Scaffolding',
    description: 'Marine scaffolding operations',
  },
  {
    id: uuidv4(),
    title: 'Confined Space Entry',
    description: 'Confined space operations certification',
  },
  {
    id: uuidv4(),
    title: 'Confined Space Rescue',
    description: 'Confined space rescue operations',
  },
  {
    id: uuidv4(),
    title: 'Working at Height',
    description: 'High elevation work certification',
  },
  {
    id: uuidv4(),
    title: 'Height Rescue Operations',
    description: 'High elevation rescue certification',
  },
  {
    id: uuidv4(),
    title: 'Gas Testing',
    description: 'Marine gas testing certification',
  },
  {
    id: uuidv4(),
    title: 'Hot Work Safety',
    description: 'Hot work operations certification',
  },
  {
    id: uuidv4(),
    title: 'Lock Out Tag Out',
    description: 'LOTO procedures certification',
  },
  {
    id: uuidv4(),
    title: 'Permit to Work',
    description: 'Work permit system certification',
  },
  {
    id: uuidv4(),
    title: 'Risk Assessment',
    description: 'Marine risk assessment certification',
  },
  {
    id: uuidv4(),
    title: 'Incident Investigation',
    description: 'Marine incident investigation',
  },
  {
    id: uuidv4(),
    title: 'Behavioral Safety',
    description: 'Behavioral based safety certification',
  },
  {
    id: uuidv4(),
    title: 'Maritime Leadership',
    description: 'Maritime leadership certification',
  },
  {
    id: uuidv4(),
    title: 'Crew Management',
    description: 'Crew resource management certification',
  },
  {
    id: uuidv4(),
    title: 'Cultural Awareness',
    description: 'Maritime cultural awareness training',
  },
  {
    id: uuidv4(),
    title: 'Maritime Communication',
    description: 'Maritime communication certification',
  },
  {
    id: uuidv4(),
    title: 'Maritime English',
    description: 'Maritime English language certification',
  },
  {
    id: uuidv4(),
    title: 'Fatigue Management',
    description: 'Maritime fatigue management',
  },
  {
    id: uuidv4(),
    title: 'Stress Management',
    description: 'Maritime stress management',
  },
  {
    id: uuidv4(),
    title: 'Mental Health First Aid',
    description: 'Maritime mental health support',
  },
  {
    id: uuidv4(),
    title: 'Cyber Security',
    description: 'Maritime cyber security certification',
  },
  {
    id: uuidv4(),
    title: 'IT Systems',
    description: 'Maritime IT systems management',
  },
  {
    id: uuidv4(),
    title: 'Network Security',
    description: 'Ship network security certification',
  },
  {
    id: uuidv4(),
    title: 'Data Management',
    description: 'Maritime data management certification',
  },
  {
    id: uuidv4(),
    title: 'Maritime Compliance',
    description: 'Maritime regulatory compliance',
  },
  {
    id: uuidv4(),
    title: 'Maritime Law',
    description: 'Basic maritime law certification',
  },
  {
    id: uuidv4(),
    title: 'Marine Insurance',
    description: 'Marine insurance certification',
  },
  {
    id: uuidv4(),
    title: 'Claims Management',
    description: 'Maritime claims handling certification',
  },
  {
    id: uuidv4(),
    title: 'Maritime Finance',
    description: 'Maritime financial management',
  },
  {
    id: uuidv4(),
    title: 'Maritime Procurement',
    description: 'Maritime purchasing certification',
  },
  {
    id: uuidv4(),
    title: 'Inventory Management',
    description: 'Ship inventory control certification',
  },
  {
    id: uuidv4(),
    title: 'Planned Maintenance',
    description: 'Planned maintenance system certification',
  },
  {
    id: uuidv4(),
    title: 'Project Management',
    description: 'Maritime project management',
  },
  {
    id: uuidv4(),
    title: 'Quality Control',
    description: 'Maritime quality control certification',
  },
  {
    id: uuidv4(),
    title: 'Waste Management',
    description: 'Marine waste management certification',
  },
  {
    id: uuidv4(),
    title: 'Green Ship Operations',
    description: 'Sustainable shipping certification',
  },
  {
    id: uuidv4(),
    title: 'Energy Efficiency',
    description: 'Ship energy efficiency certification',
  },
  {
    id: uuidv4(),
    title: 'Carbon Management',
    description: 'Ship carbon footprint management',
  },
  {
    id: uuidv4(),
    title: 'Water Treatment',
    description: 'Ship water treatment certification',
  },
  {
    id: uuidv4(),
    title: 'Air Emissions',
    description: 'Ship air emissions management',
  },
];
