// This file was generated by AI(Claude 3.5 Sonnet model)

import { Title } from './crew';
import { v4 as uuidv4 } from 'uuid';

const titles: Title[] = [
  {
    id: uuidv4(),
    name: 'Captain',
    description: "Ship's Master",
  },
  {
    id: uuidv4(),
    name: 'Chief Officer',
    description: 'First Mate',
  },
  {
    id: uuidv4(),
    name: 'Second Officer',
    description: 'Navigation Officer',
  },
  {
    id: uuidv4(),
    name: 'Chief Engineer',
    description: 'Head of Engineering',
  },
  {
    id: uuidv4(),
    name: 'Second Engineer',
    description: 'Engineering Officer',
  },
  {
    id: uuidv4(),
    name: 'Third Engineer',
    description: 'Engineering Officer',
  },
  {
    id: uuidv4(),
    name: 'Deck Cadet',
    description: 'Trainee Officer',
  },
  {
    id: uuidv4(),
    name: 'Chief Cook',
    description: 'Head of Galley',
  },
  {
    id: uuidv4(),
    name: 'Bosun',
    description: 'Deck Supervisor',
  },
  {
    id: uuidv4(),
    name: 'Able Seaman',
    description: 'Deck Crew',
  },
  {
    id: uuidv4(),
    name: 'Electrician',
    description: 'Electrical Engineer',
  },
  {
    id: uuidv4(),
    name: 'Oiler',
    description: 'Engine Room Rating',
  },
  {
    id: uuidv4(),
    name: 'Third Officer',
    description: 'Deck Officer',
  },
  {
    id: uuidv4(),
    name: 'Fourth Engineer',
    description: 'Engineering Officer',
  },
  {
    id: uuidv4(),
    name: 'Radio Officer',
    description: 'Communications Officer',
  },
  {
    id: uuidv4(),
    name: 'Steward',
    description: 'Hospitality Staff',
  },
  {
    id: uuidv4(),
    name: 'Deck Fitter',
    description: 'Maintenance Specialist',
  },
  {
    id: uuidv4(),
    name: 'Pumpman',
    description: 'Cargo Operations',
  },
  {
    id: uuidv4(),
    name: 'Motorman',
    description: 'Engine Room Rating',
  },
  {
    id: uuidv4(),
    name: 'Wiper',
    description: 'Engine Room Assistant',
  },
];

export default titles;
